server:
  port: 8081

spring:
  application:
    name: user-service
  threads:
    virtual:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/taskflow_users
    username: taskflow
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true

jwt:
  secret: "0OL3hz0pZb6pqe6yKvcHFwCqKwIaQZmT9RlSMfgcmRx"
